name: starter
recipe: wordpress
env_file:
  - .env.example
config:
  webroot: wordpress
  php: '8.1'
events:
  post-start:
    appserver: |
      composer install --working-dir=/app --no-progress --no-interaction
tooling:
  acorn:
    service: appserver
    cmd: wp --path=/app/wordpress acorn
