name: starter
recipe: wordpress
env_file:
  - .env.example
excludes:
  - vendor
  - node_modules
config:
  webroot: wordpress
  php: "8.1"
  via: nginx
  database: mariadb
  cache: redis
  xdebug: true
services:
  appserver:
    overrides:
      # See: https://github.com/docker/for-linux/issues/264#issuecomment-763555307
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        PHP_IDE_CONFIG: "${PHP_IDE_CONFIG:-serverName=appserver}"
        XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug}"
        XDEBUG_CONFIG: "${XDEBUG_CONFIG:-client_host=host.docker.internal discover_client_host=true}"
    build:
      - composer install --working-dir=/app --no-progress --no-interaction --no-progress
tooling:
  acorn:
    service: appserver
    cmd: wp --path=/app/wordpress acorn
